rm -f user-data-cloudstack1 meta-data-cloudstack1
rm -f user-data-cloudstack2 meta-data-cloudstack2
rm -f user-data-cloudstack3 meta-data-cloudstack3
rm -f user-data-cloudstack4 meta-data-cloudstack4
rm -f user-data-cloudstack5 meta-data-cloudstack5
rm -f user-data-cloudstack6 meta-data-cloudstack6
rm -f user-data-cloudstack7 meta-data-cloudstack7
rm -f user-data-cloudstack8 meta-data-cloudstack8
rm -f user-data-cloudstack9 meta-data-cloudstack9
rm -f user-data-cloudstack10 meta-data-cloudstack10
